import type { ProcessCategory } from './types';

// ─── Stałe polskiego rynku pracy — marzec 2026 ──────────────────
export const EMPLOYER_COST_MULTIPLIER = 1.2048;   // ZUS 20.48%
export const STANDARD_MONTHLY_HOURS = 168;
export const NATIONAL_AVG_SALARY = 8_735;          // PLN brutto
export const MIN_WAGE = 4_806;
export const TAX_RELIEF_RATE = 0.50;               // ulga na robotyzację 50%
export const COMPOUND_GROWTH_RATE = 0.15;           // +15% efektywność AI/rok
export const WORKING_WEEKS_PER_MONTH = 4.33;

// ─── Branże (dropdown Krok 3) ────────────────────────────────────
export const INDUSTRIES = [
  'IT i technologie',
  'Finanse i bankowość',
  'Produkcja',
  'E-commerce',
  'Usługi profesjonalne',
  'Handel detaliczny',
  'Logistyka i transport',
  'Budownictwo',
  'Edukacja',
  'Ochrona zdrowia',
  'Administracja publiczna',
  'Inne',
] as const;

// ─── 10 kategorii procesów z realnymi danymi PL ─────────────────
export const PROCESS_CATEGORIES: ProcessCategory[] = [
  // 1. FINANSE I KSIĘGOWOŚĆ
  {
    id: 'finanse',
    name: 'Finanse i Księgowość',
    icon: 'Wallet',
    description: 'Faktury, księgowość, raporty finansowe, rozliczenia podatkowe, reconciliacja',
    avgMonthlySalary: 13_500,
    salaryRange: { min: 6_000, max: 26_000 },
    overallAutomationRate: 0.70,
    keyMetric: { label: 'Redukcja błędów', value: '90%' },
    color: '#2563EB',
    tasks: [
      {
        id: 'fin-invoices',
        name: 'Przetwarzanie faktur',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 500,
        automationRate: 0.80,
        errorRateHuman: 0.02,
        errorRateAI: 0.003,
      },
      {
        id: 'fin-bookkeeping',
        name: 'Księgowość bieżąca',
        avgMinutesPerUnit: 15,
        unitsPerMonthPerEmployee: 120,
        automationRate: 0.60,
        errorRateHuman: 0.015,
        errorRateAI: 0.005,
      },
      {
        id: 'fin-reporting',
        name: 'Raporty finansowe',
        avgMinutesPerUnit: 45,
        unitsPerMonthPerEmployee: 20,
        automationRate: 0.65,
        errorRateHuman: 0.03,
        errorRateAI: 0.005,
      },
      {
        id: 'fin-tax',
        name: 'Rozliczenia podatkowe',
        avgMinutesPerUnit: 30,
        unitsPerMonthPerEmployee: 15,
        automationRate: 0.55,
        errorRateHuman: 0.025,
        errorRateAI: 0.008,
      },
      {
        id: 'fin-reconciliation',
        name: 'Reconciliacja płatności',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 200,
        automationRate: 0.85,
        errorRateHuman: 0.02,
        errorRateAI: 0.002,
      },
    ],
  },

  // 2. HR I REKRUTACJA
  {
    id: 'hr',
    name: 'HR i Rekrutacja',
    icon: 'UsersRound',
    description: 'Screening CV, onboarding, urlopy, payroll, zarządzanie procesem rekrutacji',
    avgMonthlySalary: 10_000,
    salaryRange: { min: 7_000, max: 14_000 },
    overallAutomationRate: 0.65,
    keyMetric: { label: 'Czas rekrutacji', value: '-75%' },
    color: '#7C3AED',
    tasks: [
      {
        id: 'hr-cv-screening',
        name: 'Screening CV',
        avgMinutesPerUnit: 12,
        unitsPerMonthPerEmployee: 200,
        automationRate: 0.75,
        errorRateHuman: 0.15,
        errorRateAI: 0.05,
      },
      {
        id: 'hr-scheduling',
        name: 'Umawianie rozmów rekrutacyjnych',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 80,
        automationRate: 0.85,
        errorRateHuman: 0.05,
        errorRateAI: 0.01,
      },
      {
        id: 'hr-onboarding',
        name: 'Onboarding nowych pracowników',
        avgMinutesPerUnit: 120,
        unitsPerMonthPerEmployee: 5,
        automationRate: 0.60,
        errorRateHuman: 0.08,
        errorRateAI: 0.02,
      },
      {
        id: 'hr-leave',
        name: 'Zarządzanie urlopami',
        avgMinutesPerUnit: 5,
        unitsPerMonthPerEmployee: 150,
        automationRate: 0.90,
        errorRateHuman: 0.03,
        errorRateAI: 0.005,
      },
      {
        id: 'hr-payroll',
        name: 'Obsługa payroll',
        avgMinutesPerUnit: 20,
        unitsPerMonthPerEmployee: 50,
        automationRate: 0.55,
        errorRateHuman: 0.02,
        errorRateAI: 0.005,
      },
    ],
  },

  // 3. OBSŁUGA KLIENTA
  {
    id: 'obsluga-klienta',
    name: 'Obsługa Klienta',
    icon: 'Headset',
    description: 'Odpowiedzi na maile, czat, routing ticketów, FAQ, obsługa reklamacji',
    avgMonthlySalary: 6_500,
    salaryRange: { min: 4_806, max: 9_000 },
    overallAutomationRate: 0.80,
    keyMetric: { label: 'Czas odpowiedzi', value: '-97%' },
    color: '#059669',
    tasks: [
      {
        id: 'cs-email',
        name: 'Odpowiedzi na e-maile klientów',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 400,
        automationRate: 0.80,
        errorRateHuman: 0.05,
        errorRateAI: 0.02,
      },
      {
        id: 'cs-chat',
        name: 'Obsługa czatu na żywo',
        avgMinutesPerUnit: 6,
        unitsPerMonthPerEmployee: 500,
        automationRate: 0.85,
        errorRateHuman: 0.04,
        errorRateAI: 0.015,
      },
      {
        id: 'cs-tickets',
        name: 'Routing i kategoryzacja ticketów',
        avgMinutesPerUnit: 3,
        unitsPerMonthPerEmployee: 600,
        automationRate: 0.90,
        errorRateHuman: 0.10,
        errorRateAI: 0.02,
      },
      {
        id: 'cs-faq',
        name: 'Odpowiedzi na FAQ',
        avgMinutesPerUnit: 5,
        unitsPerMonthPerEmployee: 300,
        automationRate: 0.95,
        errorRateHuman: 0.03,
        errorRateAI: 0.01,
      },
      {
        id: 'cs-complaints',
        name: 'Obsługa reklamacji',
        avgMinutesPerUnit: 20,
        unitsPerMonthPerEmployee: 60,
        automationRate: 0.50,
        errorRateHuman: 0.08,
        errorRateAI: 0.03,
      },
    ],
  },

  // 4. SPRZEDAŻ I CRM
  {
    id: 'sprzedaz',
    name: 'Sprzedaż i CRM',
    icon: 'TrendingUp',
    description: 'Lead scoring, follow-upy, zarządzanie pipeline\'em, propozycje, kontrakty',
    avgMonthlySalary: 11_000,
    salaryRange: { min: 7_000, max: 18_000 },
    overallAutomationRate: 0.55,
    keyMetric: { label: 'Więcej leadów', value: '+451%' },
    color: '#DC2626',
    tasks: [
      {
        id: 'sales-lead-scoring',
        name: 'Scoring i kwalifikacja leadów',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 200,
        automationRate: 0.70,
        errorRateHuman: 0.20,
        errorRateAI: 0.08,
      },
      {
        id: 'sales-followup',
        name: 'Follow-up e-maile i sekwencje',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 300,
        automationRate: 0.85,
        errorRateHuman: 0.05,
        errorRateAI: 0.02,
      },
      {
        id: 'sales-pipeline',
        name: 'Zarządzanie pipeline\'em CRM',
        avgMinutesPerUnit: 5,
        unitsPerMonthPerEmployee: 150,
        automationRate: 0.50,
        errorRateHuman: 0.10,
        errorRateAI: 0.03,
      },
      {
        id: 'sales-proposals',
        name: 'Generowanie ofert i propozycji',
        avgMinutesPerUnit: 45,
        unitsPerMonthPerEmployee: 20,
        automationRate: 0.40,
        errorRateHuman: 0.08,
        errorRateAI: 0.03,
      },
    ],
  },

  // 5. MARKETING
  {
    id: 'marketing',
    name: 'Marketing',
    icon: 'Megaphone',
    description: 'Social media, content, kampanie e-mail, analityka, SEO monitoring',
    avgMonthlySalary: 10_000,
    salaryRange: { min: 5_500, max: 18_000 },
    overallAutomationRate: 0.60,
    keyMetric: { label: 'Więcej contentu', value: '5×' },
    color: '#E11D48',
    tasks: [
      {
        id: 'mkt-social',
        name: 'Publikacja w social media',
        avgMinutesPerUnit: 15,
        unitsPerMonthPerEmployee: 120,
        automationRate: 0.80,
        errorRateHuman: 0.05,
        errorRateAI: 0.02,
      },
      {
        id: 'mkt-content',
        name: 'Tworzenie treści i copywriting',
        avgMinutesPerUnit: 60,
        unitsPerMonthPerEmployee: 30,
        automationRate: 0.50,
        errorRateHuman: 0.08,
        errorRateAI: 0.04,
      },
      {
        id: 'mkt-email',
        name: 'Kampanie e-mail marketing',
        avgMinutesPerUnit: 30,
        unitsPerMonthPerEmployee: 15,
        automationRate: 0.75,
        errorRateHuman: 0.06,
        errorRateAI: 0.02,
      },
      {
        id: 'mkt-analytics',
        name: 'Analityka i raportowanie',
        avgMinutesPerUnit: 25,
        unitsPerMonthPerEmployee: 25,
        automationRate: 0.70,
        errorRateHuman: 0.10,
        errorRateAI: 0.03,
      },
      {
        id: 'mkt-seo',
        name: 'Monitoring SEO i optymalizacja',
        avgMinutesPerUnit: 20,
        unitsPerMonthPerEmployee: 20,
        automationRate: 0.60,
        errorRateHuman: 0.12,
        errorRateAI: 0.04,
      },
    ],
  },

  // 6. ADMINISTRACJA
  {
    id: 'administracja',
    name: 'Administracja',
    icon: 'FileText',
    description: 'Dokumenty, planowanie spotkań, rezerwacje, wprowadzanie danych, archiwizacja',
    avgMonthlySalary: 7_000,
    salaryRange: { min: 4_806, max: 10_000 },
    overallAutomationRate: 0.65,
    keyMetric: { label: 'Mniej pracy admin', value: '-30%' },
    color: '#CA8A04',
    tasks: [
      {
        id: 'admin-docs',
        name: 'Zarządzanie dokumentami',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 300,
        automationRate: 0.70,
        errorRateHuman: 0.05,
        errorRateAI: 0.01,
      },
      {
        id: 'admin-scheduling',
        name: 'Planowanie spotkań i kalendarze',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 150,
        automationRate: 0.85,
        errorRateHuman: 0.08,
        errorRateAI: 0.02,
      },
      {
        id: 'admin-data-entry',
        name: 'Wprowadzanie danych',
        avgMinutesPerUnit: 5,
        unitsPerMonthPerEmployee: 500,
        automationRate: 0.85,
        errorRateHuman: 0.03,
        errorRateAI: 0.003,
      },
      {
        id: 'admin-travel',
        name: 'Rezerwacje podróży służbowych',
        avgMinutesPerUnit: 20,
        unitsPerMonthPerEmployee: 15,
        automationRate: 0.60,
        errorRateHuman: 0.04,
        errorRateAI: 0.01,
      },
    ],
  },

  // 7. IT I OPERACJE
  {
    id: 'it-operacje',
    name: 'IT i Operacje',
    icon: 'Server',
    description: 'Monitoring systemów, triage ticketów, backup, provisioning użytkowników',
    avgMonthlySalary: 13_500,
    salaryRange: { min: 7_500, max: 20_000 },
    overallAutomationRate: 0.50,
    keyMetric: { label: 'MTTR szybciej', value: '-70%' },
    color: '#6366F1',
    tasks: [
      {
        id: 'it-monitoring',
        name: 'Monitoring i alerty systemowe',
        avgMinutesPerUnit: 5,
        unitsPerMonthPerEmployee: 400,
        automationRate: 0.80,
        errorRateHuman: 0.05,
        errorRateAI: 0.01,
      },
      {
        id: 'it-tickets',
        name: 'Triage ticketów IT',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 250,
        automationRate: 0.70,
        errorRateHuman: 0.12,
        errorRateAI: 0.03,
      },
      {
        id: 'it-provisioning',
        name: 'Provisioning kont użytkowników',
        avgMinutesPerUnit: 15,
        unitsPerMonthPerEmployee: 40,
        automationRate: 0.85,
        errorRateHuman: 0.04,
        errorRateAI: 0.005,
      },
      {
        id: 'it-backup',
        name: 'Zarządzanie backupami',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 60,
        automationRate: 0.90,
        errorRateHuman: 0.02,
        errorRateAI: 0.002,
      },
    ],
  },

  // 8. LOGISTYKA I ŁAŃCUCH DOSTAW
  {
    id: 'logistyka',
    name: 'Logistyka i Łańcuch Dostaw',
    icon: 'Truck',
    description: 'Zamówienia, inwentaryzacja, koordynacja wysyłek, komunikacja z dostawcami',
    avgMonthlySalary: 8_500,
    salaryRange: { min: 5_500, max: 13_000 },
    overallAutomationRate: 0.55,
    keyMetric: { label: 'Redukcja kosztów', value: '-20%' },
    color: '#0891B2',
    tasks: [
      {
        id: 'log-orders',
        name: 'Przetwarzanie zamówień',
        avgMinutesPerUnit: 10,
        unitsPerMonthPerEmployee: 300,
        automationRate: 0.75,
        errorRateHuman: 0.04,
        errorRateAI: 0.008,
      },
      {
        id: 'log-inventory',
        name: 'Zarządzanie zapasami',
        avgMinutesPerUnit: 8,
        unitsPerMonthPerEmployee: 200,
        automationRate: 0.60,
        errorRateHuman: 0.06,
        errorRateAI: 0.02,
      },
      {
        id: 'log-shipping',
        name: 'Koordynacja wysyłek',
        avgMinutesPerUnit: 12,
        unitsPerMonthPerEmployee: 150,
        automationRate: 0.65,
        errorRateHuman: 0.05,
        errorRateAI: 0.015,
      },
      {
        id: 'log-suppliers',
        name: 'Komunikacja z dostawcami',
        avgMinutesPerUnit: 15,
        unitsPerMonthPerEmployee: 80,
        automationRate: 0.50,
        errorRateHuman: 0.07,
        errorRateAI: 0.02,
      },
    ],
  },

  // 9. PRAWO I COMPLIANCE
  {
    id: 'prawo',
    name: 'Prawo i Compliance',
    icon: 'Scale',
    description: 'Analiza umów, monitoring compliance, przegląd dokumentów, aktualizacja polityk',
    avgMonthlySalary: 14_000,
    salaryRange: { min: 9_000, max: 25_000 },
    overallAutomationRate: 0.45,
    keyMetric: { label: 'Szybszy przegląd', value: '-60%' },
    color: '#9333EA',
    tasks: [
      {
        id: 'legal-contracts',
        name: 'Analiza i przegląd umów',
        avgMinutesPerUnit: 60,
        unitsPerMonthPerEmployee: 30,
        automationRate: 0.55,
        errorRateHuman: 0.08,
        errorRateAI: 0.03,
      },
      {
        id: 'legal-compliance',
        name: 'Monitoring compliance (RODO, KSeF)',
        avgMinutesPerUnit: 30,
        unitsPerMonthPerEmployee: 40,
        automationRate: 0.60,
        errorRateHuman: 0.10,
        errorRateAI: 0.03,
      },
      {
        id: 'legal-docs',
        name: 'Generowanie dokumentów prawnych',
        avgMinutesPerUnit: 45,
        unitsPerMonthPerEmployee: 25,
        automationRate: 0.40,
        errorRateHuman: 0.06,
        errorRateAI: 0.02,
      },
      {
        id: 'legal-policy',
        name: 'Aktualizacja polityk wewnętrznych',
        avgMinutesPerUnit: 90,
        unitsPerMonthPerEmployee: 5,
        automationRate: 0.35,
        errorRateHuman: 0.05,
        errorRateAI: 0.02,
      },
    ],
  },

  // 10. DANE I RAPORTOWANIE
  {
    id: 'dane',
    name: 'Dane i Raportowanie',
    icon: 'BarChart3',
    description: 'Generowanie raportów, konsolidacja danych, dashboardy, śledzenie KPI',
    avgMonthlySalary: 11_000,
    salaryRange: { min: 7_000, max: 16_000 },
    overallAutomationRate: 0.70,
    keyMetric: { label: 'Redukcja błędów', value: '90%' },
    color: '#0D9488',
    tasks: [
      {
        id: 'data-reports',
        name: 'Generowanie raportów',
        avgMinutesPerUnit: 30,
        unitsPerMonthPerEmployee: 40,
        automationRate: 0.80,
        errorRateHuman: 0.08,
        errorRateAI: 0.01,
      },
      {
        id: 'data-consolidation',
        name: 'Konsolidacja danych z wielu źródeł',
        avgMinutesPerUnit: 20,
        unitsPerMonthPerEmployee: 60,
        automationRate: 0.85,
        errorRateHuman: 0.10,
        errorRateAI: 0.02,
      },
      {
        id: 'data-dashboards',
        name: 'Aktualizacja dashboardów',
        avgMinutesPerUnit: 15,
        unitsPerMonthPerEmployee: 50,
        automationRate: 0.90,
        errorRateHuman: 0.05,
        errorRateAI: 0.005,
      },
      {
        id: 'data-kpi',
        name: 'Śledzenie i analiza KPI',
        avgMinutesPerUnit: 25,
        unitsPerMonthPerEmployee: 30,
        automationRate: 0.65,
        errorRateHuman: 0.12,
        errorRateAI: 0.03,
      },
    ],
  },
];
